---
cp4ba:
- project: cp4ba
  collateral_project: cp4ba-collateral
  openshift_cluster_name: "{{ env_id }}"
  openshift_storage_name: custom
  accept_licenses: true
  state: installed
  cpfs_profile_size: small # Profile size which affect replicas and resources of Pods of CPFS as per https://www.ibm.com/docs/en/cpfs?topic=operator-hardware-requirements-recommendations-foundational-services

  # Section for Cloud Pak for Business Automation itself
  cp4ba:
    # Set to false if you don't want to install (or remove) CP4BA
    enabled: true # Currently always true
    profile_size: small # Profile size which affect replicas and resources of Pods as per https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=pcmppd-system-requirements
    patterns:
      foundation: # Foundation pattern, always true - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__foundation
        optional_components:
          bas: true # Business Automation Studio (BAS) 
          bai: true # Business Automation Insights (BAI)
          ae: false # Application Engine (AE)
      decisions: # Operational Decision Manager (ODM) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__odm
        enabled: false
        optional_components:
          decision_center: true # Decison Center (ODM)
          decision_runner: true # Decison Runner (ODM)
          decision_server_runtime: true # Decison Server (ODM)
        # Additional customization for Operational Decision Management
        # Contents of the following will be merged into ODM part of CP4BA CR yaml file. Arrays are overwritten.
        cr_custom:
          spec:
            odm_configuration:
              decisionCenter:
                # Enable support for decision models
                disabledDecisionModel: false
      decisions_ads: # Automation Decision Services (ADS) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__ads
        enabled: false
        optional_components:
          ads_designer: true # Designer (ADS)
          ads_runtime: true # Runtime (ADS)
        gen_ai: # https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/latest?topic=services-configuring-generative-ai-secret
          apiKey: <watsonx_ai_api_key>
          authUrl: https://iam.bluemix.net/identity/token
          mlUrl: https://us-south.ml.cloud.ibm.com
          projectId: <project_id>              
      content: # FileNet Content Manager (FNCM) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__ecm
        enabled: false
        optional_components:
          cmis: true # Content Management Interoperability Services (FNCM - CMIS)
          css: true # Content Search Services (FNCM - CSS)
          es: true # External Share (FNCM - ES)
          tm: true # Task Manager (FNCM - TM)
          ier: true # IBM Enterprise Records (FNCM - IER)
          icc4sap: false # IBM Content Collector for SAP (FNCM - ICC4SAP) - Currently not implemented
      application: # Business Automation Application (BAA) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__baa
        enabled: false
        optional_components:
          app_designer: true # App Designer (BAA)
          ae_data_persistence: true # App Engine data persistence (BAA)
      document_processing: # Automation Document Processing (ADP) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__adp
        enabled: false
        optional_components: 
          document_processing_designer: true # Designer (ADP)
        # Additional customization for Automation Document Processing
        # Contents of the following will be merged into ADP part of CP4BA CR yaml file. Arrays are overwritten.
        cr_custom:
          spec:
            ca_configuration:
              # GPU config as described on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=resource-configuring-document-processing
              deeplearning:
                gpu_enabled: false
                nodelabel_key: nvidia.com/gpu.present
                nodelabel_value: "true"
              ocrextraction:
                use_iocr: none # Allowed values: "none" to uninstall, "all" or "auto" to install (these are aliases)                         
      workflow: # Business Automation Workflow (BAW) - https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.1?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__baw
        enabled: false
        optional_components:
          baw_authoring: true # Workflow Authoring (BAW) - always keep true if workflow pattern is chosen. BAW Runtime is not implemented.
          kafka: true # Will install a kafka cluster and enable kafka service for workflow authoring.
  
  # Section for IBM Process mining
  pm:
    # Set to false if you don't want to install (or remove) Process Mining
    enabled: false
    # Additional customization for Process Mining
    # Contents of the following will be merged into PM CR yaml file. Arrays are overwritten.
    cr_custom:
      spec:
        processmining:
          storage:
            # Disables redis to spare resources as per https://www.ibm.com/docs/en/process-mining/1.13.2?topic=configurations-custom-resource-definition
            redis:
              install: false  

  # Section for IBM Robotic Process Automation
  rpa:
    # Set to false if you don't want to install (or remove) RPA
    enabled: false
    # Additional customization for Robotic Process Automation
    # Contents of the following will be merged into RPA CR yaml file. Arrays are overwritten.
    cr_custom:
      spec:
        # Configures the NLP provider component of IBM RPA. You can disable it by specifying 0. https://www.ibm.com/docs/en/rpa/21.0?topic=platform-configuring-rpa-custom-resources#basic-setup
        nlp:
          replicas: 1

  # Section for Asset Repository
  asset_repo:
    # Set to false if you don't want to install (or remove) Asset Repo
    enabled: false # Currently not implemented

  # Set to false if you don't want to install (or remove) CloudBeaver (PostgreSQL, DB2, MSSQL UI)
  cloudbeaver_enabled: false

  # Set to false if you don't want to install (or remove) Roundcube
  roundcube_enabled: false

  # Set to false if you don't want to install (or remove) Cerebro
  cerebro_enabled: false

  # Set to false if you don't want to install (or remove) AKHQ
  akhq_enabled: false

  # Set to false if you don't want to install (or remove) Mongo Express
  mongo_express_enabled: false
  
  # Set to false if you don't want to install (or remove) phpLDAPAdmin
  phpldapadmin_enabled: false

  # Set to false if you don't want to install (or remove) OpenSearch Dashboards
  opensearch_dashboards_enabled: false
