---
global_config:
  environment_name: cloudpak
  cloud_platform: existing-ocp
  env_id: ocp
  confirm_destroy: True

openshift:
- name: "{{ env_id }}"
  ocp_version: 4.14
  cluster_name: PATCHED_BY_JOB
  domain_name: PATCHED_BY_JOB
  gpu:
    install: True
  openshift_ai:
    install: True
    channel: fast
  mcg:
    install: False
    storage_type: storage-class
    storage_class: ibm-spectrum-scale-sc
  openshift_storage:
  - storage_name: custom
    storage_type: custom
    ocp_storage_class_file: ibm-spectrum-scale-sc
    ocp_storage_class_block: ibm-spectrum-scale-sc
